-- Local Docker reset for the Northstar demo dataset.
-- Internal users are intentionally excluded so their existing demo credentials survive.
TRUNCATE TABLE
  billing_schedules,
  credit_notes,
  invoice_lines,
  payments,
  invoices,
  subscription_lines,
  deal_alerts,
  fulfillment_allocations,
  backorders,
  order_items,
  orders,
  negotiation_comments,
  negotiation_requests,
  approval_actions,
  approval_requests,
  audit_logs,
  quotation_portal_tokens,
  quotation_items,
  quotations,
  portal_tokens,
  customer_users,
  warehouse_stock,
  warehouses,
  upsell_rules,
  price_list_items,
  products,
  category_discount_limits,
  customers,
  subscription_plans,
  price_lists,
  product_categories
CASCADE;
